### ISSUE TITLE
Implement medium screen design

### ISSUE THREAD

**Issue by stripedpajamas** [teacherfund/TeacherFund_next#100]
We have designs for medium sized screens:

- [The main page design](https://xd.adobe.com/spec/39899b04-1c47-452f-7902-d76fed55d62e-4fb8/screen/e94f8970-114b-4351-8e6f-6e2d2546d6bf/iPad-1/)
- [The menu](https://xd.adobe.com/spec/39899b04-1c47-452f-7902-d76fed55d62e-4fb8/screen/923eeaff-e5c6-4c78-b793-c002eb03aeb0/iPad-4/)
- [The donate page](https://xd.adobe.com/spec/39899b04-1c47-452f-7902-d76fed55d62e-4fb8/screen/a940e16d-c82e-4b32-8370-f84d547b7b72/iPad-2/)

Acceptance criteria:
- theteacherfund.com, when loaded on medium sized screen (viewport size 768x1024), conforms to the designs linked above

**Comment by jackpaulcollins** [comment]
I can do this!

**Comment by jackpaulcollins** [comment]
@joelwass @stripedpajamas 

I'm trying to understand how you have already made the page dynamic, and upon resizing the screen with the developer tools/React tab open I'm not seeing any classNames update. Can you point me in the right direction in how you're implementing these queries?

**Comment by korlando7** [comment]
@jackpaulcollins FWIW, TeacherFund is using [Tachyons](https://tachyons.io/) for styling. All of the class names are always present no matter what the size of the screen is. Each class added might do something different for the responsiveness of the site.

**Comment by DustinHaefele** [comment]
I've been working through these today.  Finished a few sections.  I'll tinker with it tomorrow and see how far I can get and I'll put in a pull request for what I've done.

**Comment by joelwass** [comment]
Sweet thanks @DustinHaefele. Don't hesitate to put in a PR for a work in progress so we can assess as necessary

**Comment by hi-matbub** [comment]
I'll be spending some time contributing to this today, if there's anything in particular let me know & I'll focus on that. Otherwise I'll be going from top to bottom

**Comment by joelwass** [comment]
awesome @hi-matbub ! i think one thing to note is people have contributed before so a lot of this could already be done, but any marginal improvement is always appreciated!
