### ISSUE TITLE
Implement small screen design

### ISSUE THREAD

**Issue by stripedpajamas** [teacherfund/TeacherFund_next#101]
We have designs for medium sized screens:

- [The main page design](https://xd.adobe.com/spec/39899b04-1c47-452f-7902-d76fed55d62e-4fb8/screen/c4126a77-a62e-470d-a5b7-aa70583b0db4/iPhone-6-7-8-1/)
- [The menu](https://xd.adobe.com/spec/39899b04-1c47-452f-7902-d76fed55d62e-4fb8/screen/e0771c69-47bd-49bc-9742-3295e955ea38/iPhone-6-7-8-4/)
- [The donate page](https://xd.adobe.com/spec/39899b04-1c47-452f-7902-d76fed55d62e-4fb8/screen/84848f3f-eb3b-4f0d-ad89-90e8b0dd95bc/iPhone-6-7-8-2/)

Acceptance criteria:
- theteacherfund.com, when loaded on small sized screen (viewport size 375x666), conforms to the designs linked above

**Comment by SinghVikram97** [comment]
I would like to work on it

**Comment by joelwass** [comment]
that'd be great @SinghVikram97

**Comment by SinghVikram97** [comment]
Should I start working?

**Comment by joelwass** [comment]
Any time you'd like! @SinghVikram97

**Comment by korlando7** [comment]
@SinghVikram97 are you currently working on this? If not I am going to assign this to myself to complete.

**Comment by ralph1786** [comment]
@korlando7 can I work on it or did you complete it?

**Comment by joelwass** [comment]
I think this is mostly done, thanks @ralph1786 , closing for now
