### ISSUE TITLE
Audit desktop design

### ISSUE THREAD

**Issue by stripedpajamas** [teacherfund/TeacherFund_next#102]
This issue can be closed once a careful eye has examined the current website and confirmed that it conforms to the design.

- [The main page](https://xd.adobe.com/spec/39899b04-1c47-452f-7902-d76fed55d62e-4fb8/screen/3f125505-b3ab-4a53-a97f-d33cf0ab1bb4/Web-1920-1/)
- [The donate page](https://xd.adobe.com/spec/39899b04-1c47-452f-7902-d76fed55d62e-4fb8/screen/813240b2-010b-4a2c-afc4-e2977677d2fc/Web-1920-2/)

Any deviations from the design can be logged and fixed as a part of this issue.

**Comment by mahanthathreyee** [comment]
Hi, could I contributing to this issue?

**Comment by joelwass** [comment]
Yes of course!

**Comment by mahanthathreyee** [comment]
I would like to clarify a few things,
Does the following come under this issue:

1. Positioning items
2. Addition of missing items (such as "Explore Projects" link in ,
3. Is there a guideline on class names
4. Is the audit to be done only 1920 x 1080 viewport or can other desktop viewport such as 1366 x 768 etc. are also inclusive in the audit

**Comment by joelwass** [comment]
1) yes
2) no need to _add_ anymore items (good question!)
3) tachyons.io is used for all our classnames and styling, please do not make custom classes
4) all desktop viewports should look roughly like the "desktop" designs
5) not strict!

**Comment by joelwass** [comment]
Issue has been solved with sufficient PR's for desktop design. closing for now
