### ISSUE TITLE
Add paypal button to donate page

### ISSUE THREAD

**Issue by joelwass** [teacherfund/TeacherFund_next#104]
Add OR donate with paypal button to donate page

**Comment by msk4862** [comment]
Do we have to just add a paypal button or implement its functionality also?

**Comment by joelwass** [comment]
I need to set up a PayPal account to get you the public account key, then the functionality and “adding of the button” should be the same task.

I can do that tonight

**Comment by msk4862** [comment]
Okay, I'll start with coding part

**Comment by msk4862** [comment]
@joelwass Are you done with setting up PayPal account?

**Comment by joelwass** [comment]
I'm working on getting a business verification document to paypal in order to get the API key set up, sorry for the delay @msk4862

**Comment by joelwass** [comment]
Ah here we go

add this to the html where the button should go

```<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick" />
<input type="hidden" name="hosted_button_id" value="5BZAW3NKL9L9W" />
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />
<img alt="" border="0" src="https://www.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1" />
</form>
```

and then i believe this should work

**Comment by joelwass** [comment]
might need some styling foo

**Comment by msk4862** [comment]
@joelwass I've already added a paypal button and functionality, Now you need to add your CLIENT ID (in pages/donate.js) and test the added functinality.

**Comment by joelwass** [comment]
No work remains except business logistics. Waiting for tax EIN so i can set up our paypal business side of things
