### ISSUE TITLE
ensure footer is always at bottom of page (initially off screen) for each page

### ISSUE THREAD

**Issue by joelwass** [teacherfund/TeacherFund_next#11]
Fix styling like this where the footer is on page initially when it should be off

<img width="1400" alt="screen shot 2019-02-10 at 9 38 11 am" src="https://user-images.githubusercontent.com/7344422/52537105-99d6ce00-2d17-11e9-8ac1-a71a155c7f35.png">

**Comment by joelwass** [comment]
looks still to be on the page

<img width="1391" alt="screen shot 2019-02-11 at 7 32 14 pm" src="https://user-images.githubusercontent.com/7344422/52609901-cbdd5280-2e33-11e9-8bc2-4a69196a814a.png">

**Comment by stripedpajamas** [comment]
You would need more content on that page if you want it to not show

**Comment by stripedpajamas** [comment]
If you move the footer down on that page right now you'd see the pencil picture end and ugly gray background appear
