### ISSUE TITLE
Componentize repeating elements

### ISSUE THREAD

**Issue by korlando7** [teacherfund/TeacherFund_next#128]
We have a lot of elements that can be turned into components in order to DRY up the codebase.

**For example:**
Any of the info / statistic cards

**Todo:**
- [ ] Turn any common element into a reusable component
- [ ] Make component styling consistent

**Comment by davidlanger** [comment]
Hi! I started on this little bit and would really like to continue.

**Comment by korlando7** [comment]
@davidlanger sounds good!

**Comment by capndave** [comment]
@davidlanger Let me know if you'd like me to take on a few of the elements, and which ones if so!

**Comment by BarrieLAJ** [comment]
Should this issue br closed?

**Comment by joelwass** [comment]
This issue is ongoing and can still be worked on, however more technical design might be necessary before doing work as the easy components have been completed

**Comment by BarrieLAJ** [comment]
Okay will look for some elements I can work on.
