### ISSUE TITLE
Fix responsive styles

### ISSUE THREAD

**Issue by korlando7** [teacherfund/TeacherFund_next#129]
Fix main header section:
- [x] adjust section width on small and medium screens
- [x] Address x-small width mobile styling
- [x] Fix "what we provide" content image from 500px to ~740px
- [x] add same content image on small screen

**Comment by wale-bant** [comment]
Hi, I'd like to work on this.

**Comment by maloney8** [comment]
Hey! I would like to work on this one.

**Comment by meowwwls** [comment]
Hey, @maloney8 and @wale-bant ! @korlando7 is working on this issue and has submitted a pull request with the work they've already done.
