### ISSUE TITLE
add in global font specifics according to style guide

### ISSUE THREAD

**Issue by joelwass** [teacherfund/TeacherFund_next#13]
Header: Oswald medium, 20 pt font, 24 pt leading
Text: Lato regular, 12 pt font, 16 pt leading
Pull Quote: Lato light, 40 pt font, 50 pt leading

**Comment by andrewkoung** [comment]
Hi @joelwass! 
Did you want anything that is related to a header, text, and pull quote follow that css template? Any suggestable ideas on how you wanted this done?

**Comment by jfeng43** [comment]
Let me see if I can implement it.

**Comment by jfeng43** [comment]
Hi, I have submitted a code request for this feature. In this request, I only add the global style for the nav elements (I assume this is the "header" element that you mentioned in the issue).

**Comment by joelwass** [comment]
Awesome, thanks @jfeng43, it looks great! Chances you want to implement the text font as well?

**Comment by joelwass** [comment]
fixed.
