### ISSUE TITLE
Increase nav padding to align with designs 

### ISSUE THREAD

**Issue by joelwass** [teacherfund/TeacherFund_next#136]
This is what currently exists: 
![image](https://user-images.githubusercontent.com/7344422/66531884-37aab480-eac2-11e9-8010-18b15f88903b.png)

Modify nav padding to look more like this: ![image](https://user-images.githubusercontent.com/7344422/66531848-206bc700-eac2-11e9-96d9-0873733aa401.png)

**Comment by edwards-j** [comment]
I can handle this one!

**Comment by anibalajt** [comment]
check PR

**Comment by maloney8** [comment]
Hey! I would like to work on this issue.
