### ISSUE TITLE
Second section: info stats needs adjusting

### ISSUE THREAD

**Issue by joelwass** [teacherfund/TeacherFund_next#137]
What we have: 
<img width="1390" alt="Screen Shot 2019-10-09 at 6 36 10 PM" src="https://user-images.githubusercontent.com/7344422/66532296-c9ff8800-eac3-11e9-82fa-676d50f9510e.png">

title text "We believe that by providing funding to public school teachers, we can support exemplary teaching, increase retention, and impact student success." should be tf-dark-gray color and increased text size slightly

what it should be: 
<img width="1052" alt="Screen Shot 2019-10-09 at 6 58 23 PM" src="https://user-images.githubusercontent.com/7344422/66533162-c8838f00-eac6-11e9-9bb1-38cb3e5af1b4.png">

**Comment by sliee17** [comment]
Can I do this?

**Comment by joelwass** [comment]
Of course!
