### ISSUE TITLE
Make font sizes consistent and in line with design

### ISSUE THREAD

**Issue by korlando7** [teacherfund/TeacherFund_next#150]
Currently our font sizes are not consistent throughout the app. Follow the [designs](https://xd.adobe.com/spec/39899b04-1c47-452f-7902-d76fed55d62e-4fb8/) and audit the font sizes for the provided screen sizes (mobile, tablet, desktop). Make sure font sizes are visually correct and consistent.

- [ ] evaluate and update font sizing for all mobile, tablet, and desktop screen sizes.

**Comment by arturoalviar** [comment]
Hey, can I take this?

**Comment by joelwass** [comment]
Definitely! @arturoalviar Don't hesitate to work with @korlando7 on specifics

**Comment by arturoalviar** [comment]
I am going through the [homepage screen](https://xd.adobe.com/spec/39899b04-1c47-452f-7902-d76fed55d62e-4fb8/screen/3f125505-b3ab-4a53-a97f-d33cf0ab1bb4/Web-1920-1) and noticed that most font sizes do not match the [Tachyons's type scale](http://tachyons.io/docs/typography/scale/). 

When using the type scale classes, some headings are barely off (e.g. banner heading is 100px in design comp vs Tachyons's f-headline which is 6rem ~96px) and others fall in between two classes (e.g. index__metric is 70px in the design comp while f1 is 48px and f-5/f-subheadinline is 80px). 

The coding standards require Tachyons, so what would be the best approach @korlando7? As of now, I have added the type scale classes that bring the site's type to be as close as possible to the design.

**Comment by erynrat** [comment]
Hi Arturo, thanks for bringing this up. Definitely learned something new. Can you provide the standardized text sizes are used (in px) and I will update the designs so you aren't guessing?

**Comment by nikhilgupta2001** [comment]
can i work on this

**Comment by joelwass** [comment]
of course! @nikhilgupta2001

**Comment by chaudhariyash10** [comment]
Is this issue closed or if not Can give it a shot?

**Comment by joelwass** [comment]
I think it's roughly solved so i'll close for now, thanks @chaudhariyash10
