### ISSUE TITLE
Styling of Menu (Desktop and Mobile)

### ISSUE THREAD

**Issue by erynrat** [teacherfund/TeacherFund_next#161]
Hi all, 

Thanks for all of your great work on this site so far. I'm hoping that by coming in and adding a few more design-focused edits, we can get the site looking its best. :) See below for my changes:

**Desktop Menu:** 
- Add a transition to the fill / hover state of the Donate button. Maybe .3 or .4 seconds?
- Make the donate button shorter, more like this: 
![image](https://user-images.githubusercontent.com/25090440/68180128-8122de00-ff60-11e9-90ec-5dfff6e125ae.png)
- Add hover state to "Our Mission" so it becomes 25% lighter than original color. 
- Add 50% more space between Our Mission and Donate Button. 
- Make logo 50% larger (meaning the white nav bar may have to get slightly bigger but mainly the logo should just take up more space and be a little closer to the white nav bar's edges. 
![image](https://user-images.githubusercontent.com/25090440/68180221-e37bde80-ff60-11e9-9763-b44979e92997.png)

**Tablet Menu:** 
- Make logo 25% larger and make sure it is centered in the white nav bar vertically
My design: 
![image](https://user-images.githubusercontent.com/25090440/68181481-7dde2100-ff65-11e9-8292-6318d569f983.png)

Current look:
![image](https://user-images.githubusercontent.com/25090440/68181482-85052f00-ff65-11e9-9124-b429d7177f20.png)

- In pop-up menu, delete the 'Home' option as people will know to tap the logo. 
- In the pop-up menu, list Our Mission first then have Donate in a button similar to that of the desktop version. Here is my design (with more pages than TTF currently has): 
![image](https://user-images.githubusercontent.com/25090440/68181552-d01f4200-ff65-11e9-97eb-7a5d0845c3be.png)
- Add more space between each menu item
- Make sure X in upper left corner is in the same location as the hamburger menu icon
_- Is it possible to make the hamburger menu icon animate into the X so they seem to be one thing?_

**Mobile Menu:** 
- Logo should have a little more left margin
- Make sure logo is centered in white nav bar, it looks too high right now
- Same issues as Tablet menu for the most part. 

Any questions, let me know!

**Comment by erynrat** [comment]
@joelwass Can you remind me how to label these? I don't see the checkbox that this article is referring to: 
https://help.github.com/en/github/managing-your-work-on-github/applying-labels-to-issues-and-pull-requests

**Comment by neusaguera** [comment]
I can work on this!

**Comment by deepank120896** [comment]
@erynrat @neusaguera 
Has this issue been addressed?

**Comment by joelwass** [comment]
Yes! sorry @deepank120896 sometimes github doesn't auto close issues
