### ISSUE TITLE
Styling of Hero Image (Responsive)

### ISSUE THREAD

**Issue by erynrat** [teacherfund/TeacherFund_next#162]
Can someone make these style edits to the hero image and text on the homepage?

**Large Laptop (1440px wide):** 
- Move hero image down so pencil tips aren't so close to white nav bar
- What is the next size down from the current text "Funding Teachers. Empowering Students."? This is looking a little big to me, but if it is a big jump down I will reconsider. 
- Can you made the tagline below bolder so it is a little more readable. Here is my original design: 
![image](https://user-images.githubusercontent.com/25090440/68180777-fb546200-ff62-11e9-9aa2-08327fb56a52.png)

**Smaller Laptop (1024px wide):** 
- Move hero image down so pencil tips aren't beneath white nav bar
- Header and tagline jump too far to the left when going from 1440px wide to 1024px wide. I'm hoping these basically look the same (more like 1440px wide) but with less left and right margin. 

**Tablet (768px wide):** 
So the tablet needs a good amount of help. :)
Here is a screenshot of how I want it to be upon load:
![image](https://user-images.githubusercontent.com/25090440/68181023-de6c5e80-ff63-11e9-9857-afe4c8a40f2f.png)

Here is how it is currently: 
![image](https://user-images.githubusercontent.com/25090440/68181038-eaf0b700-ff63-11e9-8c36-bd18373407bf.png)

Changes: 
- Make hero image go down to fold on tablet on first load
- Pencils should still be visible with pencil tips under the logo but not under the nav bar
- Header and tagline shift down and below the pencils, slightly smaller than desktop size (what are the text size standards and I can update my design if need be?)

**Mobile (425px wide and below):**
- Move hero image down and to the left so pencil tips are visible and below the logo
- Move text down so not overlapping pencils
- Give more margin on left of text
- Increase line height in both the header and tagline

Here is my design: 
![image](https://user-images.githubusercontent.com/25090440/68181334-eed10900-ff64-11e9-9094-472606be021a.png)

Here is the current site: 
![image](https://user-images.githubusercontent.com/25090440/68181340-f690ad80-ff64-11e9-9164-75b21773ab82.png)
 
Any questions, let me know!

**Comment by JennaKoslowski** [comment]
I can work on this!

**Comment by erynrat** [comment]
Thank you, Jenna! Let me know if you have any questions and I'll try to answer.

**Comment by JennaKoslowski** [comment]
So I've been trying to figure out if there'd be an easier/ less intrusive way to solve the space issue between the navigational part and the pencil tips and I think a lot of it could be solved if the image and text were in their own component. Are you cool with that or do you see a different way?

**Comment by joelwass** [comment]
I think that works, @stripedpajamas what do you think

**Comment by stripedpajamas** [comment]
For sure

**Comment by Jay-Topher** [comment]
Hi, has this issue been resolved? I would like to work on it.

**Comment by joelwass** [comment]
Hi Jay! It actually has - sorry i didn't close it. A PR was submit about a week ago
