### ISSUE TITLE
Migrate react-stripe-elements to @stripe/react-stripe-js

### ISSUE THREAD

**Issue by joelwass** [teacherfund/TeacherFund_next#165]
Stripe has a newer version of elements and loading

i think this is as simple as removing the stripeProvider element and using the loadStripe promise instead
`import { Elements, StripeProvider } from 'react-stripe-elements'`
should become:
`import {Elements} from '@stripe/react-stripe-js'`

and loading stripe should be done with 
`const stripePromise = loadStripe('<stripe_pk_key>')`

this will also allow us to remove client conditional rendering phrase: `{process.browser &&` 

requirements:
* update packages used (uninstall old stripe library and install new)
* update how we load the stripe key
* remove StripeProvider entirely
* remove conditional client rendering
* pass in stripe to the stripe Elements element `<Elements stripe={stripePromise}>`
* test

**Comment by zachsnoek** [comment]
@joelwass May I try this one?

**Comment by joelwass** [comment]
Of course! @zachsnoek

**Comment by zachsnoek** [comment]
I've not used Stripe before; what would be an appropriate way to test this?

**Comment by joelwass** [comment]
If it renders, you’re in business! I’ll Review the PR to make sure you didn’t miss anything
