### ISSUE TITLE
No thumbnail image

### ISSUE THREAD

**Issue by joelwass** [teacherfund/TeacherFund_next#170]
We need a thumbnail image so when donors tweet that they've just donated, an image shows up when our URL is expanded.

Best image to use is: /static/images/Logo.png

**Comment by DhyeyLalseta** [comment]
Hey! I'll try to start on this!

**Comment by dankb82** [comment]
Did [this PR](https://github.com/teacherfund/TeacherFund_next/pull/171) resolve the issue or is it still open?

**Comment by dhyxy** [comment]
From how much I tried with it, I think it's fixed now. If anyone else wants to test it out I used: 

[Facebook Debugger](https://developers.facebook.com/tools/debug/)

[Twitter Validator](https://cards-dev.twitter.com/validator)

**Comment by joelwass** [comment]
I believe it's fixed! Sorry, the issue wasn't tagged in the PR so it didn't auto fix
