### ISSUE TITLE
Refactor SCSS structure

### ISSUE THREAD

**Issue by korlando7** [teacherfund/TeacherFund_next#18]
This project could really benefit from using [BEM](http://getbem.com/) styling across all styles.

I would avoid having all of the classes be camel case.

**Part One**

A lot of the scss files are just css inside a scss file. One big thing is minimal to no nesting. `donate.scss` almost follows these guidelines but does not have any nesting.

For example in `emailcapture.scss`:

**Currently**
```css
.emailCaptureContent {}
.captureInput {}
.captureButton {}
.captureInput > input {}
```

**Should Be**
```css
.email-capture {
    &__content {
        @media screen and (max-width: 600px) {}
    }
    &__input {
        input {}
    }
    &__button {
        @media screen and (max-width: 600px) {}
    }
 }
```

**Part Two**

Use variables as much as possible. Definitely want to use:

`$small-screen: 600px`
vs typing that value across the app

**Comment by joelwass** [comment]
submit a PR :)

**Comment by joelwass** [comment]
ALSO should go in our contributor guide in the readme

**Comment by jfeng43** [comment]
Hi, I am a newbie in open source community and I'd like to make contribution to this!

**Comment by jfeng43** [comment]
I just submitted a pull request for refactoring email capture component. Let me know if this is the right way to style the code.

**Comment by DavidLi119** [comment]
Hello, I am a beginner in the open source community and I would like to make a contribution to this issue.

**Comment by joelwass** [comment]
no longer applicable, using taychon
