### ISSUE TITLE
Buttons and text overlapping.

### ISSUE THREAD

**Issue by DeadSpoon18** [teacherfund/TeacherFund_next#184]
![2](https://user-images.githubusercontent.com/58849158/96182249-daf29d00-0f52-11eb-962e-43907da6adde.png)
![1](https://user-images.githubusercontent.com/58849158/96182260-dded8d80-0f52-11eb-99cf-6cc2d3439244.png)
when website is viewed on mobile phone, these parts are overlapping.

**Comment by rmit-s3722599-Minh-Le** [comment]
Hi! I'm new to contributing, kind of my first time too and I want to take on this task if that's ok? ^^

**Comment by joelwass** [comment]
Definitely! This might be tough as it only can be reproduced on Tablet Width so definitely reach out with any questions.

Familiarizing yourself with Tachyons.io (our current styling method) and chakra-ui (our newly desired styling method) will be helpful as well!

**Comment by rmit-s3722599-Minh-Le** [comment]
Hi there! 
If I want to add something like ```min-width: fit-content```, but it doesn't have it in the Tachyons.io styling method, how can I add the style to the button?

**Comment by joelwass** [comment]
Hi @rmit-s3722599-Minh-Le  sorry for the late response!

We're trying to move to Chakra UI styling, so if it's a div you're trying to replace, you'd use the "Box" component from chakra, and then you can set minWidth as a prop on the Box component. 

https://chakra-ui.com/box

if you let me know what pieces of code you're trying to edit i can advise further! thanks for contributing :)

**Comment by rmit-s3722599-Minh-Le** [comment]
Noo it's fine!!
Thanks for the response, and I'll look into that!! :)

**Comment by rmit-s3722599-Minh-Le** [comment]
Hi @joelwass 

I'm nearly done, fixed the overlappings. Just having trouble trying to make the buttons the same height after some of the fixes and edits.
 
The buttons heights are relative the same in a normal width size browsing in like the computer:

<img src="https://user-images.githubusercontent.com/41458636/98538942-9fdc5300-22df-11eb-8446-541c33362fae.png" width="500" height="500">


But when you begin to shrink it, at a certain point, it'll look like this: 

<img src="https://user-images.githubusercontent.com/41458636/98538292-a3bba580-22de-11eb-87d4-ea241571c2a1.png" width="500" height="500">


Thanks for helping me! :)

**Comment by joelwass** [comment]
I think that's fine, for odd dimensions like that, before it hits the breakpoint of "small" screensize that's probably fine.

Send up a PR, thanks so much for working on this :)

**Comment by rmit-s3722599-Minh-Le** [comment]
Thank you for giving me the opportunity to help!! :)
There happens to be a merge conflict (edit: I fixed it I think!) though, i'll send the pull request!
