### ISSUE TITLE
Scroll to the Top feature on FAQ page

### ISSUE THREAD

**Issue by nmoras** [teacherfund/TeacherFund_next#185]
The FAQ page on the site has a lot of content.
A feature like the 'scroll to Top' button would help people to get back to the top of the page immediately and also, as the users don't scroll down to the answer on their own, a click on the question suddenly takes them down to the answers, adding a scroll to Top button might be intuitive.  Can I please work on it? I could work on it and if it adds to usability, you can choose to add or skip.

**Comment by joelwass** [comment]
Definitely! Thanks @nmoras ! i like that idea.

Please use Chakra-UI when implementing the link or button

**Comment by nmoras** [comment]
@joelwass thank you... sure
