### ISSUE TITLE
Change the width of the division

### ISSUE THREAD

**Issue by Zhoha28** [teacherfund/TeacherFund_next#191]
![Capture](https://user-images.githubusercontent.com/32241004/100956552-ae183a80-353e-11eb-9462-389a749d93c7.PNG)
Change the width of the div to 100% so the teal color (#336e7b) covers the entire background.

**Comment by joelwass** [comment]
It's supposed to be 94% to show that the budget is lacking, to go along with the comment!

**Comment by Zhoha28** [comment]
oh, my bad

**Comment by joelwass** [comment]
No worries :) thanks for checking it out!
