### ISSUE TITLE
Writing code segment on CONTRIBUTING.md

### ISSUE THREAD

**Issue by gccornejo441** [teacherfund/TeacherFund_next#228]
_Please note: all design should be made with [our home page style](https://github.com/teacherfund/TeacherFund_next/blob/master/HomePageDesign.pdf) in mind._

Does this simply go to a pdf of the current Homepage TeacherFund website?

**Comment by joelwass** [comment]
oh weird, hmmmmm it was a PDF of the design for the page, not a pdf of the actual website. let me add it back
