### ISSUE TITLE
The scrollToTop icon does not come suddenly even if you have sroll the page 

### ISSUE THREAD

**Issue by Hirenachhaada** [teacherfund/TeacherFund_next#229]
https://user-images.githubusercontent.com/95188259/193397946-99512b3c-d333-4a74-815e-03f8a28acb56.mp4

**Comment by abdulhaseeb036** [comment]
This is what I actually analyze, good to see this issue already presents.

**Comment by joelwass** [comment]
Yes - the scroll to top button should only show after you have scrolled past the main view port, not immediately, otherwise you are scrolling to view content you can still see
