### ISSUE TITLE
add tests / testing framework

### ISSUE THREAD

**Issue by stripedpajamas** [teacherfund/TeacherFund_next#28]
choose a testing framework and get some basic component unit tests written

**Comment by joelwass** [comment]
only test critical user journeys (CUJ's) for integration tests:

Most critical user journey: Jackie wants to donate to teacher fund, she goes to website, she donates, jackie leaves and carries on her day.
2nd most critical user journey: Tammy the Teacher wants funds. She goes to the website, logs in to her Teacher account, and requests money and/or supplies via the request portal

**Comment by jfeng43** [comment]
Hi @joelwass just want to know, which testing framework are you going to use? Any guidance on doing integration tests? I write unit tests most of the time, but when it comes to integration tests, I don't know how to implement them in a systematic way.

**Comment by nidamunir** [comment]
Can i write unit tests?

**Comment by joelwass** [comment]
Yes! I think @stripedpajamas and I need to consider testing frameworks. I'd assume we want to run just integration tests on a headless browser, i don't think there's need for unit tests on our FE.

Thoughts?

**Comment by stripedpajamas** [comment]
Our front end is a little too in flux right now for unit tests. After #100 #101 and #102 are closed, I think it would be safe to add some Enzyme tests to keep any future code changes from regressing on the design.

In regard to integration tests, for now I think it would be fine for now to implement unit tests around our client side API wrapper with mocks and unit tests around our [server side](https://github.com/teacherfund/TeacherFund_api) API logic. 

The testing frameworks for these unit tests can probably be standard Mocha+Chai, as I think that would be the most accessible. That implementation detail is up to @joelwass

**Comment by joelwass** [comment]
Fixed ^
