### ISSUE TITLE
TwoItemSwitcher text camouflaged with the background

### ISSUE THREAD

**Issue by andrewkoung** [teacherfund/TeacherFund_next#33]
Hi there! I'm a student hoping to get into some open source development. I've built the project and was looking at the SCSS structure issue, but realized that the TwoItemSwitcher text's color was matching with the white background making it impossible for me to see the option. Small issue, but I've made a pull request anyways to change the text color.

**Comment by joelwass** [comment]
i noted on your pull request that it might be best to pass in a prop of the color instead. since the background will be different in different situations.

also if you add "fixes #33" to your pull request description it will close this issue when we merge the PR!
