### ISSUE TITLE
find hourglass react component

### ISSUE THREAD

**Issue by joelwass** [teacherfund/TeacherFund_next#39]
Fine hourglass react component to display on our work page as to how much money is in our coffers

**Comment by abdiG** [comment]
Hi @joelwass, i am new to open source and would like to contribute to this project. If no one is working on this issue may work on it. If i can, where should i place the hourglass

**Comment by joelwass** [comment]
On the account page! 

within the `account--stats` div

**Comment by joelwass** [comment]
no longer applicable
