### ISSUE TITLE
implement table for our work page with all payout and payment info

### ISSUE THREAD

**Issue by joelwass** [teacherfund/TeacherFund_next#40]
create basic table with all info of cash inflows and outflows pulled from the API. this belongs as a component to be used in the ourwork.js page

**Comment by pbrahmbhatt3** [comment]
Hi,
I would like to work on this issue. However, I am new to this project. Any suggestions on where can I start from. @joelwass

**Comment by joelwass** [comment]
Hi @pbrahmbhatt3 ! Thanks for your interest!

I think this would be a good starter task, we just want to create a table component that will be able to show a list of data (columns being something like: type, donor/recipient, amount, and date) and then the rows being data fetched from the api (you don't have to worry about this yet it can be a separate task as the API side isn't done yet). 

Long story short implementing a table component that could take in props for columns and rows, and used a jsx for loop to iterate over the rows, would be awesome! let me know if i can help further

**Comment by jfeng43** [comment]
@joelwass I have some questions:
1. since the API is not ready yet, should I write some static data for the table?
2. what are the columns?
3. how should the table look like?
4. where should I put the table

It would be great if you can attach a draft of the new page so that I can understand better your goal.

**Comment by joelwass** [comment]
sure! 

columns should be: "type", "donor/recipient", "amount", and "date". the table should be in chronological order with the top most rows being the most recent. 

The table should be in it's own component and you can follow this guide to create just a simple css grid https://medium.com/evodeck/responsive-data-tables-with-css-grid-3c58ecf04723

**Comment by joelwass** [comment]
I know that's vague, we don't really have designs currently so we'll definitely have to revisit but we appreciate you helping out and getting this going!!!

**Comment by pbrahmbhatt3** [comment]
Thank for your input. I am currently working on this issue @joelwass

**Comment by joelwass** [comment]
how can i help @pbrahmbhatt3

**Comment by jfeng43** [comment]
@joelwass sounds good. I am looking into it.

**Comment by jfeng43** [comment]
Hi @joelwass , I created this pull request: https://github.com/teacherfund/TeacherFund_next/pull/67

**Comment by jfeng43** [comment]
<img width="1303" alt="table" src="https://user-images.githubusercontent.com/28817027/54881837-a1b38300-4e2a-11e9-8d0a-5638a5c27c56.png">

**Comment by jfeng43** [comment]
Please let me know your comment!

**Comment by pbrahmbhatt3** [comment]
The table looks good. However, I suppose that the background image will be removed! As it would become very difficult to read data with this image at the back.

**Comment by joelwass** [comment]
Good point @pbrahmbhatt3 . i just merged @jfeng43 's table, we'd love styling help if you have bandwidth!
