### ISSUE TITLE
wrap authenticated routes in a redirecter

### ISSUE THREAD

**Issue by stripedpajamas** [teacherfund/TeacherFund_next#69]
currently you can directly access `/account` (not sure what other pages assume a logged in state). it should instead redirect to either the home page or the login page. this might be able to be baked into the existing HOC.

**Comment by jfeng43** [comment]
@stripedpajamas , which HOC component you suggest me to add the redirection logic to?

**Comment by joelwass** [comment]
This belongs in a route guard 
https://stackoverflow.com/questions/50687015/route-guards-in-next-js-react
https://github.com/zeit/next.js/issues/153

**Comment by stripedpajamas** [comment]
Since account features have been removed, let's close this issue out. @joelwass and I will be revisiting the account architecture and once we have that nailed down we can create issues for implementation.
