### ISSUE TITLE
add post-login and post-registration pages

### ISSUE THREAD

**Issue by stripedpajamas** [teacherfund/TeacherFund_next#71]
Since registration/login are both email based, we need a page to redirect to after each that tells the user to expect an email.

**Comment by jfeng43** [comment]
Hi @stripedpajamas , I'd like to help here. Could you add more information about this issue? It would be great to have some flow charts or some pictures as reference materials.

**Comment by joelwass** [comment]
Hey @jfeng43 , this is hard to explain and was created as more of just a tracking bug. let me try to get some mocks to you asap!

**Comment by jfeng43** [comment]
> Hey @jfeng43 , this is hard to explain and was created as more of just a tracking bug. let me try to get some mocks to you asap!

Sounds good.

**Comment by pbrahmbhatt3** [comment]
I think I have an idea of how would these pages look like since I have worked on it before. Can I work on it @joelwass

**Comment by joelwass** [comment]
Absolutely, feel free

**Comment by jfeng43** [comment]
Hi @stripedpajamas @joelwass , I just added a post-registration page: https://github.com/teacherfund/TeacherFund_next/pull/73

The page can be accessed via localhost:3001/post-registration.
Please review my code change. 

Thanks

**Comment by jfeng43** [comment]
<img width="1012" alt="Screen Shot 2019-04-06 at 10 21 15 AM" src="https://user-images.githubusercontent.com/28817027/55670706-bdb91a80-5855-11e9-8203-d85a217c7789.png">

**Comment by aqeelparpia** [comment]
hello @stripedpajamas @joelwass  i added a post login Welcome page that Greets user after they have logged in. Since the login is also email based "This is a personal opinion as i dont think a user wouldnt be happy receiving emails everytime as they login unless its an activity confirmation email". Please Review. Thanks #78
