### ISSUE TITLE
show password does not work

### ISSUE THREAD

**Issue by abdiG** [teacherfund/TeacherFund_next#74]
#### In the `\signinregister` page in password field when typed a password `show` button doesn't work. I can try and see if i can do a PR for this.

![showPassword](https://user-images.githubusercontent.com/46496734/55771228-27534780-5a55-11e9-8aac-555bf035bddb.PNG)

**Comment by stripedpajamas** [comment]
Good find @abdiG -- the fix for this should actually be to remove the password field completely as we are trying to move towards a passwordless authentication scheme.

**Comment by joelwass** [comment]
I believe this was taken out in master branch, could you pull master before starting work?

**Comment by abdiG** [comment]
Hey @joelwass, just checked the master branch and the password field has been removed, so there is no need for PR. Let me know if i can help you guys with anything else.
