### ISSUE TITLE
Anti pattern for account buttons

### ISSUE THREAD

**Issue by stripedpajamas** [teacherfund/TeacherFund_next#77]
- The `buttons` array is outside the component, so changes to it will persist across app state changes (logging in and out / changing pages does not reset the `buttons` array)
- The splicing of the `buttons` array happens in the component's render function, which is called on every state change or props change -- for instance, opening/closing the drawer would re-call the render function and if the user is still logged in, re-remove and re-add the Account button to the `buttons` array

https://github.com/teacherfund/TeacherFund_next/blob/0b11ed5c66f25bdfbc31694ff6f5802da75da2bd/components/nav.js#L40

**Comment by nidamunir** [comment]
Is this issue fixed already?

**Comment by joelwass** [comment]
We currently removed the login functionality, but that's an entire feature that needs to be added back in, in which case this bug still exists! 

Let me see how close this issue is to being unblocked

**Comment by stripedpajamas** [comment]
This issue is no longer in master. Will close for now and if any other anti-patterns come up after reimplementing account management, we can open fresh issues for them.
