### ISSUE TITLE
Make two item switcher button text vertically centered

### ISSUE THREAD

**Issue by joelwass** [teacherfund/TeacherFund_next#81]
Center vertically the two item switcher text

code in: twoItemSwitcher.js
screenshot of bug: 
<img width="335" alt="Screen Shot 2019-05-03 at 2 48 26 PM" src="https://user-images.githubusercontent.com/7344422/57138303-9d2ba400-6db2-11e9-9463-541f9cdb88a5.png">

**Comment by joelwass** [comment]
All style bugs, such as this one, should use the taychon library

http://tachyons.io/docs/

**Comment by thischrisblack** [comment]
If my recent PR for the stripe input meets your needs, I'd love to work on this one as well. Let me know, and thanks!

**Comment by joelwass** [comment]
Absolutely! Thanks @thischrisblack !

**Comment by thischrisblack** [comment]
@joelwass, I just submitted PR. It says "This branch has conflicts that must be resolved," so I'm wondering if I skipped a step? I checked the upstream master before working and it said I was up to date, so please let me know if there's a problem I can fix. Thanks!

**Comment by joelwass** [comment]
fixed in above PR
