### ISSUE TITLE
Make the stripe info input the same width as the other donate form divs

### ISSUE THREAD

**Issue by joelwass** [teacherfund/TeacherFund_next#82]
Styling issue -> use taychons.io/docs

The width of the stripe input is slightly too large. using the taychon styles, align the width with the other inputs in components/donateForm.js

See screenshot for bug:
<img width="384" alt="Screen Shot 2019-05-03 at 2 50 00 PM" src="https://user-images.githubusercontent.com/7344422/57138434-f267b580-6db2-11e9-90ce-532a654e7802.png">

**Comment by thischrisblack** [comment]
Hello, this is my first time trying to contribute to open source, and it looked like an issue I could take a shot at, so I forked, cloned, branched, and npm installed, and ran npm run dev. However, on my local machine, it looks very different. The stripe form is the same width as the rest, and there is no spacing between the forms.

![stripe](https://user-images.githubusercontent.com/7775971/57157523-c4c04380-6d95-11e9-8296-8b5fd5d0fab0.JPG)

I'd love to pursue this and help out if you still need it. If so, can you tell me what I've done wrong? As I said, this is my first try ...

Thanks!

**Comment by joelwass** [comment]
Hi @thischrisblack ! Sorry about that, if you pull master you should see the issue (we just merged a major redesign). Note: the donate button in the nav is the only one that currently works, i'll fix the other one today but not sure i'll get around to it.

let me know if you have any other issues running the app and seeing the issue!

**Comment by thischrisblack** [comment]
Aha, there it is! Thank you. I'll get started.

**Comment by joelwass** [comment]
fixed in https://github.com/teacherfund/TeacherFund_next/pull/83
