### ISSUE TITLE
Make apply and donate buttons clickable on index page (get involved section)

### ISSUE THREAD

**Issue by joelwass** [teacherfund/TeacherFund_next#84]
For some reason the two buttons aren't clickable (i'm assuming it's because of some z-index garbage). code is in index.js Get Involved section

screenshot: 
<img width="1107" alt="Screen Shot 2019-05-05 at 7 26 29 AM" src="https://user-images.githubusercontent.com/7344422/57188906-35d33880-6f07-11e9-9e54-f4d1cc86c376.png">

**Comment by thischrisblack** [comment]
I'd like to give this a try.

**Comment by joelwass** [comment]
sorry @thischrisblack , was fixed in latest push

**Comment by thischrisblack** [comment]
Ah! Well, it was a fun fix and I learned something anyway.
