### ISSUE TITLE
Add mobile nav menu

### ISSUE THREAD

**Issue by korlando7** [teacherfund/TeacherFund_next#88]
Once the width of the screen is too small we need a navigation change for the `nav` component.

Let's decide what kind of layout / menu we want. I am proposing:

Logo on left and a hamburger icon on right that when clicked displays a dropdown with the menu items with `flex-column`

**Comment by stripedpajamas** [comment]
I am proposing a minimalistic inline collapse: https://tachyons.io/components/nav/logo-links-inline-collapse/index.html

**Comment by stripedpajamas** [comment]
This can be closed in favor of #100 #101
