### ISSUE TITLE
Donate page IMG conflicting with the rest of the page.

### ISSUE THREAD

**Issue by raregamer** [teacherfund/TeacherFund_next#92]
On the donate page the image seems to be conflicting with the whole layout.  The ".absolute" class and "position", look to be part of the culprit. This is blocking out the donate form and any other information that might be on the page.

**Comment by joelwass** [comment]
Thanks @raregamer! I think this is solved in a PR that is just about to be put in

**Comment by joelwass** [comment]
Fixed in https://github.com/teacherfund/TeacherFund_next/pull/93
