### ISSUE TITLE
implement twitter "Spread the word" tweet feature

### ISSUE THREAD

**Issue by joelwass** [teacherfund/TeacherFund_next#96]
When a user donates, our app takes them to the /success page. here, we want a button that says "Spread the word" (currently commented out) which will redirect them to twitter with a pre-filled tweet saying

"I just donated to The Teacher Fund, check it out at theteacherfund.com"

**Comment by vanessanaja** [comment]
I'm happy to work on this next week.

**Comment by joelwass** [comment]
Fixed in #97
