### ISSUE TITLE
Create different size images

### ISSUE THREAD

**Issue by stripedpajamas** [teacherfund/TeacherFund_next#99]
Currently our images are too big. The header image we're using is 4mb. Loading on mobile is slow.

Acceptance criteria:
- There are small, medium, and large versions of each image
- All images are compressed to the highest amount that does not affect human-eye quality
- Which size image is loaded is based on the screen size of the website user

In the near future, there may be different images for different screen sizes (not just different image sizes), but this is a good step to take in the interim.

**Comment by dr0id007** [comment]
Would like to work on this issue.

**Comment by RichardViskovic** [comment]
Hey there,

If this issue is still available, I'd like to give it a crack!

Best,
Richard

**Comment by joelwass** [comment]
Absolutely @RichardViskovic it's all yours!

**Comment by EricNewcombe** [comment]
#116 

I submitted a pull request for this issue! I'm still new to the whole open source contribution thing so hopefully I did it correctly. Let me know!

**Comment by sukanyashet** [comment]
would like to work on this

**Comment by CodeWithBlaze** [comment]
i also want to work on this issue . i am a newbie but want to contribute . I want to work with you guys @EricNewcombe and @joelwass

**Comment by shubham-sharma-2323** [comment]
Is this issue still open? I would like to work on this issue...

**Comment by joelwass** [comment]
Yes @shubham-sharma-2323 it is still open if you would like to do it!

**Comment by joelwass** [comment]
comments in this closed PR may help @shubham-sharma-2323 https://github.com/teacherfund/TeacherFund_next/pull/116

**Comment by swingleSara** [comment]
I would like to work on this if it is still open.

**Comment by joelwass** [comment]
It is @swingleSara please refer to the closed PR #116 and it's comments

**Comment by swingleSara** [comment]
I don't know how I missed that in all the comments before mine, but I
clearly see it now. Thanks!

**Comment by adityapathakk** [comment]
Hello, I'd like to take up this issue as my Hacktoberfest contribution!

**Comment by 0xClint** [comment]
Is this issue will be tagged as Hactoberfest ?

**Comment by Tyler-Pritchard** [comment]
This issue is listed on Upforgrabs.net, but it sounds like it's been closed?

**Comment by abdulhaseeb036** [comment]
I want to work on this issue, it still alive?

**Comment by joelwass** [comment]
Yes it is, it's not closed, please refer to previous comments and PR #116 for details on how to approach this

**Comment by KelvingomeX** [comment]
Hello. I would like to work on this issue.

**Comment by jmurphy1196** [comment]
Hi! I submitted #250 pull request to address this. I believe I handled the index page images. I was going to work on the other images but, I noticed since the last pull request related to this issue, it looks like you are using a new Image component. I am not sure if this component supports <picture> tags or not.

**Comment by joelwass** [comment]
fixed in #250
